### ISSUE TITLE
Is this still under progress?

### ISSUE THREAD

**Issue by wongjiahau** [andrei-markeev/ts2c#19]

**Comment by andrei-markeev** [comment]
What do you mean, the ts2c project? Yes it is still work in progress. There is a big refactoring  ongoing in the "types-refactoring" branch at the moment.

**Comment by bil-ash** [comment]
Even the types-refactoring branch also seems to be dormant for some time.
Any roadmap of when the next commit will be made to either of the branches?

**Comment by andrei-markeev** [comment]
Hi, no real roadmap as such. Just returned from the summer vacation. Will continue with ts2c when I have time!
