### ISSUE TITLE
Support for throw/catch/errors

### ISSUE THREAD

**Issue by LucaT1** [andrei-markeev/ts2c#21]
First: Amazing project would like to contribute in any way possible.

Now onto the real issue, why the support for runtime errors(throw, catch, and the Error constructor) isn't planned on being supported?

**Comment by andrei-markeev** [comment]
Nope, it isn't, at least currently.
It's possible to emulate exceptions in C with `goto`, so potentially I think it can be done at some point.

**Comment by andrei-markeev** [comment]
Good starting point: http://www.di.unipi.it/~nids/docs/longjump_try_trow_catch.html
This solution does not support case when exception is thrown inside another function though, for this we would need to arrange some sort of a stack of jmp_buf variables.

If nothing unexpected pops out, I think the implementation should actually be rather straightforward.
