### ISSUE TITLE
Multidimensional arrays

### ISSUE THREAD

**Issue by jarble** [andrei-markeev/ts2c#29]
I tried to compile this JavaScript code into C, but it seems that ts2c is not able to convert multidimensional arrays:

```
var a = 2;
var b= a+1;
var c = [[a,b],[a,b]];
console.log("Hello world!");
```

There are some errors in the translated code:

```
#include <stdio.h>
typedef short int16_t;
static int16_t a;
static int16_t b;
static void * c[2];
int main(void) {
    a = 2;
    b = a + 1;
    /* Unsupported assignment c[0][0] = a */;
    /* Unsupported assignment c[0][1] = b */;
    /* Unsupported assignment c[1][0] = a */;
    /* Unsupported assignment c[1][1] = b */;
    printf("Hello world!\n");

    return 0;
}
```

Is it feasible to translate these multi-dimensional arrays from JavaScript into C?

**Comment by andrei-markeev** [comment]
I think this is just a bug in types inference which was refactored some time ago.
I'll fix it easily.
