### ISSUE TITLE
Why int16 for numbers?

### ISSUE THREAD

**Issue by nitwhiz** [andrei-markeev/ts2c#41]
Isn't js using up to 50ish bits for numbers?
All bit-operations use 32 bit, so why not int32?

**Comment by andrei-markeev** [comment]
because the main goal of this project is to support low power microcontrollers, and there are some 16-bit microcontrollers out there that don't support 32 bit numbers at all. JavaScript of course operates mainly on 32-bit numbers (and 64-bits are also supported in later versions of standard).
