### ISSUE TITLE
`with` is as dynamic as `eval` and it's hard to implement.

### ISSUE THREAD

**Issue by zaoqi-unsafe** [andrei-markeev/ts2c#46]

**Comment by jesobreira** [comment]
Using `with` is not allowed by JS's strict mode due to the same fact. Because of JS's OO nature, it's hard to tell when a specified called method belongs to the global namespace or to the "with"-ed object. For example:

```javascript
with (myObj) {
  alert("foo") // window.alert or myObj.alert?
}
```

**Comment by andrei-markeev** [comment]
> window.alert or myObj.alert?
I don't see much difference between "with" and closures from implementation point of view to be honest. I haven't yet examined the spec in detail regarding "with", but I believe it can be implemented by creating a new scope and setting "myObj" to be the instance object.

_Dynamic_ is essentially something what is defined as a string value and then evaluated. That we don't touch. Everything else should be doable.
