### ISSUE TITLE
can  ts -> c -> wasm ?

### ISSUE THREAD

**Issue by liangzeng** [andrei-markeev/ts2c#5]
can  ts -> c -> wasm ?

**Comment by andrei-markeev** [comment]
TS2C at this point supports only 48% of ES3 standard, but I hope to get it to 100% ES3 support by the end of the year, and then will start expanding to ES2015 and TS.

So for now "ts -> c" part is not yet there, but the "c -> wasm" can be done easily using Emscripten: https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

Hope that answers your question :)

**Comment by liangzeng** [comment]
@andrei-markeev  thanks
