### ISSUE TITLE
type alias

### ISSUE THREAD

**Issue by zaoqi** [andrei-markeev/ts2c#54]
```
type st=string;
var s: st = "Hello world!";
console.log(s);
```

```
#include <stdio.h>
static const char * s;
int main(void) {
    /* Unsupported node: type st=string; */;
    s = "Hello world!";
    printf("%s\n", s);

    return 0;
}
```

**Comment by Templarian** [comment]
To go off of this thread this might tie into how to handle `number` long term.

```ts
type short = number; // Wanting to be explicit
type int32_t = number; // Use this association to set the type
type integer = int32_t;
type int64_t = number; // Use this association to set the type
type long = int64_t;
// Unsigned
type uint8_t= number; // Use this association to set the type
type char = uint8_t;
type uint16_t = number; // Use this association to set the type
type ushort = uint16_t;
type uint64_t = number; // Use this association to set the type
type ulong = uint64_t;
// Also I guess?
type float = number;
type double = number;
```

Just thinking out loud, haven't looked into the code far enough to see what his requires. Hit an instance where I need int32 due to some memory related stuff. Going to try and setup my local and look into this a little (not sure how deep this number is always `int16_t` is built in).

This project is already amazing by the way!

**Comment by andrei-markeev** [comment]
@Templarian hey, well if you want to define some types explicitly, there is an existing mechanism for that via jsdoc annotation *ctype*, used e.g. here: https://github.com/andrei-markeev/ts2c-target-esp-idf/blob/master/headers/esp_system.h/index.d.ts#L8

But numbers in general, they are quite hard, unfortunately. They need different storage, and they need conversions between number types. As soon as we detect that a number doesn't fit into `int16_t`, we need to expand the variable type into bigger number type (but first check that current platform even supports that). For this, we need detection in compile time, we need a new type, and then we need a lot of conversion/casting most likely. Very similar to how `js_var` is handled currently as I see it.

See also: https://github.com/andrei-markeev/ts2c/issues/31#issuecomment-480617053

**Comment by Templarian** [comment]
Can that be used to set a number to `int32_t`? Not sure I follow.

```ts
/** @ctype uint32_t * */
var foos: number = 10;
```

Started looking through the code trying to figure out how everything was wired up. Very much a stop gap to add type alias map, but would allow one to explicitly define the size if they know it. Would still have to wait for conversion to be handled, but easier to get around if one is explicitly setting the types.

Unfortunately it does go against the goal of `number` type magically expanding/contracting as needed like in JS, which is what one would expect. Not a bad stop gap as it can be removed later once all the conversions are in proper until then it works just to explicitly define the type.

**Comment by andrei-markeev** [comment]
I am not sure TS type alias maps well to C type alias. I think TS allows much more, C type aliases are quite restricted.

Also what you're now trying to do, it's not exactly TS anymore, but some custom language with TS syntax I guess, which should be aware of C types.

**Comment by andrei-markeev** [comment]
> Can that be used to set a number to int32_t?

currently not, I checked, it is implemented only for structures, but I think something like this is a good way to implement what you want.

**Comment by Templarian** [comment]
Would solve the issue. Do find the blow to be more readable for those wanting to be explicit.

```ts
type integer = int32_t;
type int64_t = number;
// ^ Throw that somewhere above
const foo: integer = 0x04000000;
```

vs

```ts
/**
 * @ctype uint32_t
 */
var foo: number = 0x04000000;
```

Might look into the code a bit to see if both are possible... somehow.

**Comment by andrei-markeev** [comment]
I will close this: for now I am concentrating on implementing the ES3 spec, so supporting type aliases and other TS features it is very very far away anyways, no point keeping the issue here. let's do it one by one, ES3 -> ES5 -> ES6 -> ... -> TS 😉
