### ISSUE TITLE
Issue with JS file extension.

### ISSUE THREAD

**Issue by georgy7** [andrei-markeev/ts2c#6]
Foremost, I have to say, this is a great project, and I highly interested in its success. I'm most impressed with zero-dependency output code in pure C, permissive license of the whole software. And also both Typescript and JS are widely known high-level languages. I wish you the best of luck in this endeavor.

----- 

The problem, I noticed, was the following.
I wrote the sample code in 100% JS.

```
console.log("Привет! 嗨".length);

function factorial(n) {
    if (n <= 1) {
        return 1;
    } else {
        return n * factorial(n - 1);
    }
}

console.log(factorial(19));
```

Then, I save it as `hello2.js`.

```
$ ts2c hello2.js
$ cat hello2.c 
int main(void) {
    
    return 0;
}
```

But, if I rename it to `hello2.ts`, everything is fine.

------

The second problem was the integer overflow.
`int16_t` can't handle `121645100408832000`.
It may be `double` here, but I am not sure, how this could be resolved at compile-time.
So, I got `109641728` instead.

-----

ts2c@2.0.0
node v4.2.6
npm 3.5.2
Ubuntu 16.04.2 LTS

**Comment by andrei-markeev** [comment]
Hi Georgy,

Thanks for your feedback!

Good point about ".js" extension, I'll look into that!

About numbers: you're correct, the numbers aren't fully supported for now, all numbers are currently handled as 16-bit integer as it is documented in [COVERAGE.md](https://github.com/andrei-markeev/ts2c/blob/master/COVERAGE.md).

Neither floats nor bigger integers are supported. The primary target for this project is low-level microcontrollers, so this approach should be sufficient for most cases at least in the beginning, but of course plans are to support everything according to the JavaScript specification.

Best,
Andrei
