### ISSUE TITLE
Can not compile class

### ISSUE THREAD

**Issue by RonkTsang** [andrei-markeev/ts2c#61]
I try some code in playground, and I get a Error when I try to write `class`.

``` js
// code:
function A() {
  this.a = 2
}

A.prototype.change = function () {
  this.a = 3
}
```
and I got the Error: 
```
Transpilation failed. TypeError: Cannot read property 'length' of undefined
```

**This project is cool** ~

**Comment by andrei-markeev** [comment]
`prototype` is not yet supported. Currently finalizing closures, probably prototypes will be the next step after that.

**Comment by andrei-markeev** [comment]
duplicate of #68
