### ISSUE TITLE
[question] Will this work with precompiled esnext to es3?

### ISSUE THREAD

**Issue by ackvf** [andrei-markeev/ts2c#63]
Will this work with code writen in latest JS, precompiled to ES3 and then converted to C using this tool?

**Comment by andrei-markeev** [comment]
The implementation of ES3 spec is not complete yet. Also e.g. `eval` is not planned to be supported. And finally, obviously things like DOM are completely outside of the scope. Otherwise, answer is yes.

**Comment by ackvf** [comment]
I want to run the code on an IoT device, but write in JS.

**Comment by andrei-markeev** [comment]
Hey, yes, this is exactly why I am building this project. As I mentioned, it is still work in progress though, some ES3 features aren't supported yet, so this is not yet ready for production usage. Please check README.md & COVERAGE.md for details.
