### ISSUE TITLE
C functions

### ISSUE THREAD

**Issue by usercybe** [andrei-markeev/ts2c#77]
hello, are there any way I can call c functions without getting something like this:
`/* Unsupported function call: printf("a") */;`

**Comment by neimanpinchas** [comment]
yes, I would also advocate for such a feature.

we must have a way to include raw c in the source files

Until we implement a new runtime, we should be able to use the underlying runtime

**Comment by andrei-markeev** [comment]
This is already possible, you need to create a "runtime" project similar to this one: https://github.com/andrei-markeev/ts2c-target-esp-idf. Naming is important, it should start with "ts2c-target-", for example, "tsc-target-c89".

After this, you should be able to do
```ts
import { printf } from 'ts2c-target-c89/stdio.h';

printf("a");
```
